import type { Metadata } from "next";
import "./globals.css";

import { Manrope } from "next/font/google";
import LenisProvider from "@/providers/lenis-providerlenis-provider";
import BackToTop from "@/components/layout/BackTop";
import Header from "@/components/layout/Header";
import BrandSection from "@/components/home/BrandSection";
import Footer from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/sonner";

export const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className}  antialiased`}>
        <Header />
        <BackToTop />
        <LenisProvider>{children}</LenisProvider>
        <BrandSection />
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
